language: node_js
node_js:
  - "5.6"
install:
  - npm install
  - bower install
  - npm install -g firebase-tools
after_success:
  - echo "Building project"
  - gulp build:production
  - echo "Deploying to Firebase"
  - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
